begin: '1112'
catalog: true
config: ../config/catalog.yml
cp_dir: ../catalog
end: '1112'
freq: '12'
ftp: false
ftp_dir: pub/incoming/catalog/test
ftp_server: catalog.eol.ucar.edu
month: 09
mtp: ''
now: false
raobtype: GIF:SKEWT
region: ''
rsl: ../config/sample.RSL
station_list_file: config/snstns.tbl
stnm: ''
test: ''
year: '2019'
