begin: ''
catalog: false
config: ../config/mtp.yml
cp_dir: ''
mtpdir: ../mtp
end: ''
freq: '12'
ftp: false
ftp_dir: ''
ftp_server: ''
month: ''
mtp: true
now: true
raobtype: TEXT:LIST
region: ''
rsl: ../config/sample.RSL
station_list_file: config/snstns.tbl
stnm: ''
test: false
year: ''
