# List of stations with location, description, etc
# Give path relative to RAOBget dir
station_list_file: 'config/snstns.tbl'
# Ftp data to catalog site, or cp to local dir?
ftp: True
# If ftp is Yes, need ftp_server and ftp_dir
ftp_server: 'catalog.eol.ucar.edu'
ftp_dir: 'pub/incoming/catalog/test'
# If ftp is False, need cp_dir
cp_dir: '/net/iftp2/pub/incoming/catalog/test'
